# Generated by Django 3.0.2 on 2020-03-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohjelma', '0002_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='release_year',
            field=models.IntegerField(default=2000),
        ),
    ]
