# Generated by Django 3.0.2 on 2020-03-28 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohjelma', '0003_song_release_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_name', models.CharField(max_length=500)),
                ('track_artist', models.CharField(max_length=500)),
                ('track_duration', models.IntegerField(default=200000)),
                ('track_popularity', models.IntegerField(default=100)),
            ],
        ),
    ]
