# Generated by Django 3.0.2 on 2020-04-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohjelma', '0006_auto_20200329_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='track_id',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
