# Generated by Django 3.0.2 on 2020-04-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohjelma', '0007_track_track_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='track_danceability',
            field=models.FloatField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
