# Generated by Django 3.0.2 on 2020-04-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohjelma', '0008_track_track_danceability'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='track_acousticness',
            field=models.FloatField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='track_energy',
            field=models.FloatField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='track_instrumentalness',
            field=models.FloatField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='track_key',
            field=models.IntegerField(default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='track_liveness',
            field=models.FloatField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='track_loudness',
            field=models.FloatField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='track_speechiness',
            field=models.FloatField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='track_tempo',
            field=models.FloatField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='track_valence',
            field=models.FloatField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
